### ISSUE TITLE
Misleading comment for exercise 3

### ISSUE THREAD

**Issue by futtetennista** [elmoin/dive-into-elm-exercise-II#1]
At the end of text there is the following sentence:

> Start elm reactor and check if everything works as expected.

Problem is: elm reactor [doesn't work with ports](https://github.com/elm-lang/elm-reactor/issues/36) so people not aware of this issue might be puzzled. So I'd suggest to simply delete that sentence (at least for ex. 3).

**Comment by ggb** [comment]
Yes, you are right. I was quite sure that elm reactor added support for ports with 0.17, but I could'nt find any ressources or an official announcement. But even then this sentence/part of the exercise is misleading, so I've deleted it without replacement.

Thank you!

**Comment by futtetennista** [comment]
Have a look at https://github.com/elm-lang/elm-reactor/issues/36 for more
info on the topic.
